/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   keys.h                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: mmondell <mmondell@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/06/21 11:22:43 by mmondell          #+#    #+#             */
/*   Updated: 2021/07/09 10:59:30 by mmondell         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef KEYS_H
# define KEYS_H

# define KEY_A               (0x00)
# define KEY_S               (0x01)
# define KEY_D               (0x02)
# define KEY_F               (0x03)
# define KEY_H               (0x04)
# define KEY_G               (0x05)
# define KEY_Z               (0x06)
# define KEY_X               (0x07)
# define KEY_C               (0x08)
# define KEY_V               (0x09)
# define KEY_B               (0x0B)
# define KEY_Q               (0x0C)
# define KEY_W               (0x0D)
# define KEY_E               (0x0E)
# define KEY_R               (0x0F)
# define KEY_Y               (0x10)
# define KEY_T               (0x11)
# define KEY_1               (0x12)
# define KEY_2               (0x13)
# define KEY_3               (0x14)
# define KEY_4               (0x15)
# define KEY_6               (0x16)
# define KEY_5               (0x17)
# define KEY_EQUAL           (0x18)
# define KEY_9               (0x19)
# define KEY_7               (0x1A)
# define KEY_MINUS           (0x1B)
# define KEY_8               (0x1C)
# define KEY_0               (0x1D)
# define KEY_RIGHTBRACKET    (0x1E)
# define KEY_O               (0x1F)
# define KEY_U               (0x20)
# define KEY_LEFTBRACKET     (0x21)
# define KEY_I               (0x22)
# define KEY_P               (0x23)
# define KEY_L               (0x25)
# define KEY_J               (0x26)
# define KEY_QUOTE           (0x27)
# define KEY_K               (0x28)
# define KEY_SEMICOLON       (0x29)
# define KEY_BACKLASH       (0x2A)
# define KEY_COMMA           (0x2B)
# define KEY_SLASH           (0x2C)
# define KEY_N               (0x2D)
# define KEY_M               (0x2E)
# define KEY_PERIOD          (0x2F)
# define KEY_GRAVE           (0x32)
# define KEY_KEYPADDECIMAL   (0x41)
# define KEY_KEYPADMULTIPLY  (0x43)
# define KEY_KEYPADPLUS      (0x45)
# define KEY_KEYPACLEAR     (0x47)
# define KEY_KEYPADDIVIDE    (0x4B)
# define KEY_KEYPADENTER     (0x4C)
# define KEY_KEYPADMNUS     (0x4E)
# define KEY_KEYPADEQUALS    (0x51)
# define KEY_KEYPAD0         (0x52)
# define KEY_KEYPAD1         (0x53)
# define KEY_KEYPAD2         (0x54)
# define KEY_KEYPAD3         (0x55)
# define KEY_KEYPAD4         (0x56)
# define KEY_KEYPAD5         (0x57)
# define KEY_KEYPAD6         (0x58)
# define KEY_KEYPAD7         (0x59)
# define KEY_KEYPAD8         (0x5B)
# define KEY_KEYPAD9         (0x5C)

/* 	
	KEYS THAT ARE INDEPENDANT FROM ANY DIFFERENT
	KEYBOARD LAYOUT
*/
# define KEY_RETURN			(0X24)
# define KEY_TAB			(0X30)
# define KEY_SPACE			(0X31)
# define KEY_DELETE			(0X33)
# define KEY_ESCAPE			(0x35)
# define KEY_COMMAND		(0X37)
# define KEY_SHIFT			(0X38)
# define KEY_CAPSLOCK		(0X39)
# define KEY_OPTION			(0X3A)
# define KEY_CONTROL		(0X3B)
# define KEY_RIGHTSHIFT		(0X3C)
# define KEY_RIGHTOPTION	(0X3D)
# define KEY_FUNCTION		(0X3F)
# define KEY_F17			(0X40)
# define KEY_VOLUMEUP		(0X48)
# define KEY_VOLUMEDOWN		(0X49)
# define KEY_MUTE			(0X4A)
# define KEY_F18			(0X4F)
# define KEY_F19			(0X50)
# define KEY_F20			(0X5A)
# define KEY_F5				(0X60)
# define KEY_F6				(0X61)
# define KEY_F7				(0X62)
# define KEY_F3				(0X63)
# define KEY_F8				(0X64)
# define KEY_F9				(0X65)
# define KEY_F11			(0X67)
# define KEY_F13			(0X69)
# define KEY_F16			(0X6A)
# define KEY_F14			(0X6B)
# define KEY_F10			(0X6D)
# define KEY_F12			(0X6F)
# define KEY_F15			(0X71)
# define KEY_HELP			(0X72)
# define KEY_HOME			(0X73)
# define KEY_PAGEUP			(0X74)
# define KEY_FORWARDDELETE	(0X75)
# define KEY_F4				(0X76)
# define KEY_END			(0X77)
# define KEY_F2				(0X78)
# define KEY_PAGEDOWN		(0X79)
# define KEY_F1				(0X7A)
# define KEY_LEFTARROW		(0X7B)
# define KEY_RIGHTARROW		(0X7C)
# define KEY_DOWNARROW		(0X7D)
# define KEY_UPARROW		126

#endif